[versions]
checkstyle = "10.21.0"
jib = "3.5.1"
git-properties = "2.5.4"
protobuf-plugin = "0.9.5"
sonarqube = "6.2.0.5505"
node-gradle = "7.0.2"
modernizer = "1.12.0"

[plugins]
[plugins.jib]
id = "com.google.cloud.tools.jib"
version.ref = "jib"

[plugins.git-properties]
id = "com.gorylenko.gradle-git-properties"
version.ref = "git-properties"

[plugins.protobuf]
id = "com.google.protobuf"
version.ref = "protobuf-plugin"

[plugins.modernizer]
id = "com.github.andygoossens.modernizer"
version.ref = "modernizer"
